Create liux-newbie.rst
RussianFedora/FAQ pull request #106
Opened 2022-01-08 15:33 UTC by sotnikov123

Базовые понятия

Подробно опишите какие изменения в проект вносит данный pull request:

Глава для базоых понятий

2022-01-09 09:44 UTC, xvitaly requested changes
1. Слово "newbie" aka "noob" - это мягкое ругательство в английском языке. Использовать его в проекте обучающего характера категорически нельзя.
2. У нас уже есть отдельная страница для базовых и простых вопросов - `generic-info.rst`. Соответственно, вопросы нужно разбить и переместить туда.

2022-01-09 09:44 UTC, xvitaly commented on source/liux-newbie.rst
> +О чем и зачем этот раздел?
Этот вопрос не несёт никакой смысловой нагрузки и не нужен на мой взгляд.

2022-01-09 09:44 UTC, xvitaly commented on source/liux-newbie.rst
> +    uname -a
`fpaste --sysinfo` намного лучше.

2022-01-09 09:44 UTC, xvitaly commented on source/liux-newbie.rst
> +Сначала дочитай до конца, потом вводи команды в консоли. Поехали.
Ответ на этот вопрос уже есть в FAQ: https://russianfedora.github.io/FAQ/using-system.html#system-info

2022-01-09 09:44 UTC, xvitaly commented on source/liux-newbie.rst
> +.. index:: newbie console terminal command line
Теги разделяются запятыми.

2022-01-10 08:02 UTC, sotnikov123 commented
> 1. newbie

https://translate.yandex.ru/?utm_source=main_stripe_big&lang=en-ru&text=newbie
https://translate.academic.ru/newbie/en/ru/
Я - не натив-спикер, из моих познаний негативных коннотаций не обнаружил. Есть какие-то варианты, вроде отдающего занудством beginner? - заначит пусть будет так, это лучше, чем ничего

2. generic-info - "простая страница" содержит в себе термины, которые требуют подготовки, она для людей, которые пришли из других релизов или смогли сами немного разобраться. На мой взгляд крайне необходима "совсем простая страница" для людей, которые до этого с линуксом и консолью дела не имели вовсе. Для тех, кто на "введем в консоли ххх" спросит: "что такое консоль?". Изложение в этой "совсем простой странице" должно отличаться от остального FAQ тем, что введение каждого термина должно предваряться его объяснением. Да и от "простой страницы" на версту веет бюрократией (на мой взгляд)

2022-01-10 11:01 UTC, xvitaly commented
>  Я - не натив-спикер, из моих познаний негативных коннотаций не обнаружил. Есть какие-то варианты, вроде отдающего занудством beginner? - заначит пусть будет так, это лучше, чем ничего

Единственный правильный словарь - это The Oxford English Dictionary:

![image](https://user-images.githubusercontent.com/966711/148754910-e4adc975-dca0-4b4d-a62f-7f1017b1025e.png)

Отдельная страница с 3 вопросами избыточна. Можно создать мета-вопрос вида "Что почитать новичку и как освоиться", в который включить ссылки на важные ответы из других разделов.

> Для тех, кто на "введем в консоли ххх" спросит: "что такое консоль?". Изложение в этой "совсем простой странице" должно отличаться от остального FAQ тем, что введение каждого термина должно предваряться его объяснением. Да и от "простой страницы" на версту веет бюрократией (на мой взгляд)

На мой взгляд, для такой цели нужно писать отдельную книгу. Я за поддержание единого стиля для всего FAQ.

2022-01-10 13:58 UTC, xvitaly commented
Мы обсудили и решили, что достаточно отдельной страницы. Конечно дублировать то, что уже есть в FAQ, в ней не следует.

В качестве названия будет походящим вариантом `beginners.rst`. Слово "beginners" ("начинающие") звучит намного лучше, чем newbie.

2022-01-11 14:36 UTC, closed without merging