Steam wayland native runtime
RussianFedora/FAQ pull request #117
Opened 2022-08-17 17:06 UTC by cmdorexe

Добавил описание для избавления steam от ubuntu12 runtime. Использовав нативный runtime получаем прирост в fps и избавление от рандомных вылетов.

2022-08-17 20:27 UTC, xvitaly requested changes
Требуется внести ряд изменений.

Раньше Steam в Fedora не работал без использования собственного рантайма. Возможно, @gasinvein знает больше.

2022-08-17 20:27 UTC, xvitaly commented on source/using-applications.rst
> +.. _steam, _wayland:
Название вопроса начинается с подчёркивания и не может иметь пробелов.

2022-08-17 20:27 UTC, xvitaly commented on source/using-applications.rst
> +Вылеты Steam\Dota2\CSGO в wayland?
Вопрос поставлен некорректно. Следует переформулировать, например: "Как запретить Steam использовать собственный runtime"?

2022-08-17 20:27 UTC, xvitaly commented on source/using-applications.rst
> +Установим все необходимые библиотеки для этого:
Каждый абзац начинается с одной пустой строки, иначе они будут слиты вместе при компиляции HTML/PDF.

2022-08-17 20:27 UTC, xvitaly commented on source/using-applications.rst
> +    sudo dnf install libSM*.i686 libICE*.i686 openal-soft*.i686 libnm*.i686 conky -y
Все необходимые 32-битные зависимости уже должны быть установлены пакетом Steam из RPM Fusion. Нет необходимости устанавливать их повторно. К тому же использовать глобализацию посредством символа `*` не рекомендуется, т.к. приведёт к установке ненужных `-devel` подпакетов.

2022-08-17 20:27 UTC, xvitaly commented on source/using-applications.rst
> +Проверить что все библиотеки на месте:
Все фразы должны использовать форму от третьего лица для соответствия общему стилю FAQ, т.е. "проверим", "установим", "выполним" и т.п.

2022-08-17 20:27 UTC, xvitaly commented on source/using-applications.rst
> +Если на предыдущем этапе все библеотеки найдены, переходим к отключению ubuntu12 рантайма:
"Библиотеки".

2022-08-17 20:27 UTC, xvitaly commented on source/using-applications.rst
> +    sudo sed -i "\$aSTEAM_RUNTIME=0" "/etc/environment"
Категорически не следует править `/etc/environment`. Если требуется внести какие-то правки в переменные окружения, необходимо создать файл конфигурации в `/etc/profile.d/` с именем `foo-bar.sh`.

2022-08-17 20:27 UTC, xvitaly commented on source/using-applications.rst
> +Отключаем прекеш шейдеров(Прирост только если выбран Steam Linux Runtime):
Переформулировать с использованием русского языка в соответствие с официальным переводом внутри клиента Steam.

2022-08-17 20:27 UTC, xvitaly commented on source/using-applications.rst
> +.. index:: steam, gaming, wayland
Все вопросы с различными хаками и workaround должны находиться в `tips-and-tricks.rst`. Новые вопросы всегда размещаются в конце, чтобы не ломать индекс полнотекстового поиска.

2022-08-22 19:45 UTC, cmdorexe commented
Произвёл все правки которые требовались.

2022-08-23 12:13 UTC, xvitaly commented on source/tips-and-tricks.rst
> +Избавление от ubuntu12 рантайма в STEAM лечит рандомные вылетания самого стима и многих игр, применимо к wayland.
Я бы не был столь категоричен. Многие игры как раз наоборот собраны под Ubuntu 12.04 LTS и с новыми библиотеками либо вообще откажутся запускаться, либо будут вылетать в случайных местах.

2022-08-23 12:14 UTC, xvitaly commented on source/tips-and-tricks.rst
> +    sudo dnf install libSM-1.2.3-10.*.i686 libICE-1.0.10-8.*.i686 openal-soft-1.21.1-2.*.i686 libnma-1.8.38-1.*.i686 libnma-gtk4-1.8.38-1.*.i686 conky -y
Как я уже говорил выше, символы подстановок `*` использовать не следует, как и версии, ибо в Fedora они постоянно меняются.

`conky` - это вообще не библиотека и её там явно быть не должно.

2022-08-23 12:17 UTC, xvitaly commented on source/tips-and-tricks.rst
> +    sudo sed -i "\$aexport STEAM_RUNTIME=0" "/etc/profile.d/steam.sh"
Есть более удобный и надёжный способ записи:

```
echo "export STEAM_RUNTIME=0" | sudo tee /etc/profile.d/steam.sh
```

2022-08-23 12:17 UTC, xvitaly commented on source/tips-and-tricks.rst
> +Отключаем прекеш шейдеров(Прирост только если выбран Steam Linux Runtime):
Кэш шейдеров к использованию Steam Runtime отношения не имеет.

2022-08-23 13:59 UTC, xvitaly commented on source/tips-and-tricks.rst
> +В параметрах запуска игры Совместимость(Compatibility) ставим Steam Linux Runtime.
Выше мы избавлялись от Steam Runtime, а сейчас включаем его. Противоречие в этом вижу я.

2022-08-23 15:44 UTC, cmdorexe commented on source/tips-and-tricks.rst
> +В параметрах запуска игры Совместимость(Compatibility) ставим Steam Linux Runtime.
В этом противоречие вижу тоже. Точно известно, что запускается при этом нативный Runtime.
Runtime Steam из профиля удалил:
~.local/share/Steam/ubuntu12_32/steam-runtime
~.local/share/Steam/ubuntu12_64/steam-runtime-heavy

2022-08-23 15:47 UTC, cmdorexe commented on source/tips-and-tricks.rst
> +Отключаем прекеш шейдеров(Прирост только если выбран Steam Linux Runtime):
Точно известно, что после наших манипуляций, прекеш шейдеров уменьшает производительность.

2022-08-23 15:48 UTC, cmdorexe commented on source/tips-and-tricks.rst
> +    sudo sed -i "\$aexport STEAM_RUNTIME=0" "/etc/profile.d/steam.sh"
На результат не влияет.

2022-08-23 15:49 UTC, cmdorexe commented on source/tips-and-tricks.rst
> +    sudo dnf install libSM-1.2.3-10.*.i686 libICE-1.0.10-8.*.i686 openal-soft-1.21.1-2.*.i686 libnma-1.8.38-1.*.i686 libnma-gtk4-1.8.38-1.*.i686 conky -y
Проверил без conky, полёт нормальный.

2022-08-23 15:59 UTC, cmdorexe commented on source/tips-and-tricks.rst
> +Избавление от ubuntu12 рантайма в STEAM лечит рандомные вылетания самого стима и многих игр, применимо к wayland.
Проверил на двух играх с Runtime ubuntu12. В логе видно, что она пыталась искать библиотеки по путям:
~.local/share/Steam/ubuntu12_32/steam-runtime
~.local/share/Steam/ubuntu12_64/steam-runtime-heavy
Если выбрать Steam Linux Runtime в свойствах, то использует из окружения. Очень странное поведение у этой настройки.

2022-08-23 16:02 UTC, cmdorexe commented on source/tips-and-tricks.rst
> +Избавление от ubuntu12 рантайма в STEAM лечит рандомные вылетания самого стима и многих игр, применимо к wayland.
Деградации отсутствует, за пару недель тестов на родном runtime.

2022-08-24 08:37 UTC, xvitaly commented on source/tips-and-tricks.rst
> +    sudo sed -i "\$aexport STEAM_RUNTIME=0" "/etc/profile.d/steam.sh"
Запуск sed от рута достаточно небезопасная операция. Tee всего лишь записывает полученное из пайпа в указанный файл.

2022-08-24 08:37 UTC, xvitaly commented on source/tips-and-tricks.rst
> +Отключаем прекеш шейдеров(Прирост только если выбран Steam Linux Runtime):
Использование или не использование рантайма никак не влияет на кэш шейдеров. На это может влиять лишь используемая версия mesa/nvidia, однако в runtime они не входят.

2022-08-24 08:37 UTC, xvitaly commented on source/tips-and-tricks.rst
> +В параметрах запуска игры Совместимость(Compatibility) ставим Steam Linux Runtime.
Если мы продолжаем использовать рантайм, тогда в чём смысл всей затеи?

2022-12-30 12:11 UTC, closed without merging