Add info about btrfs balance and compression
RussianFedora/FAQ pull request #96
Opened 2021-06-26 21:23 UTC by cyberMe

Добавил вопросы про балансировку и сжатие btrfs из личного опыта

2021-06-26 21:36 UTC, tim77 commented
Вредные советы.

1. Балансировка: Разработчики самой Fedora категорично [против](https://pagure.io/fedora-btrfs/project/issue/16#comment-673806).
2. Сжатие. В Fedora 34 [используется](https://fedoraproject.org/wiki/Changes/BtrfsTransparentCompression#Enable_btrfs_transparent_zstd_compression_by_default) по умолчанию `zsdt:1` сжатие.

2021-06-27 09:32 UTC, cyberMe commented
@tim77 
Балансировка. Судя по приведенной ссылке разработчики Fedora против автоматизации процесса балансировки. С этим можно согласиться, регулярный запуск лишь повысит вероятность потерять данные. 
В определённых условиях: мало свободного места, специальные операции записи, можно [исчерпать свободные для записи блоки](https://btrfs.wiki.kernel.org/index.php/Problem_FAQ#I_get_.22No_space_left_on_device.22_errors.2C_but_df_says_I.27ve_got_lots_of_space). В этом случае только балансировка сможет помочь. Полезность балансировки btrfs можно сравнить с полезностью [дефрагментации ext4](https://russianfedora.github.io/FAQ/administration.html#ext4).

Относительно сжатия, очевидно, что оно будет применяться только для [свежих установок](https://fedoraproject.org/wiki/Changes/BtrfsTransparentCompression#Upgrade.2Fcompatibility_impact) Fedora. Те, кто обновляется с предыдущих релизов должны настроить его вручную.

2021-06-27 09:42 UTC, tim77 commented
> Балансировка. Судя по приведенной ссылке разработчики Fedora против автоматизации процесса балансировки.

В том контексте в котором он ответил, против в принципе. Про определенные условия: в том и суть что, они хотят исправить полностью подобные проблемы и если советовать всем пользователям делать ребаланс, то тем самым как раз делаете то, про что он говорит и против чтобы делали не только в Fedora, но и в suse.

Вы советуете делать её регулярно и даже ссылаетесь на: _Официальная документация рекомендует выполнять балансировку регулярно._

Официальная документация трижды устарела о чем постоянно говорят как федора разработчики так и сами btrfs разработчики и не является истинной первой инстанции.

> Относительно сжатия, очевидно, что оно будет применяться только для свежих установок Fedora. Те, кто обновляется с предыдущих релизов должны настроить его вручную.

Так же должно быть очевидно, что умолчания для того и умолчания и только благодаря им сами разработчики надеятся отловить постепенно и проработать оставшиеся баги. Очевидно, что менять их не нужно предлагать всем подряд, а кто хочет, всегда найдет доки и информацию о том, как поэкспериментировать со сжатием в btrfs.

2021-06-27 13:15 UTC, xvitaly commented
Если переместить в раздел Tips and Tricks, то будет нормально, на мой взгляд.

2021-06-27 13:18 UTC, xvitaly requested changes

2021-06-27 13:18 UTC, xvitaly commented on source/administration.rst
> +=========================================
Количество знаков равенства должно быть на 3 больше.

2021-06-27 13:18 UTC, xvitaly commented on source/administration.rst
> +BTRFS использует двухуровневую структуру хранения данных: пространство поделено на *фрагменты*, которые содержат *блоки данных*. При длительной эксплуатации в файловой системе может возникать большое
Желательно добавить внутреннюю ссылку на якорь BTRFS:

```
:ref:`BTRFS <fs-btrfs>`
```

2021-06-27 13:18 UTC, xvitaly commented on source/administration.rst
> +- `SysadminGuide <https://btrfs.wiki.kernel.org/index.php/SysadminGuide#Balancing>`_
Маркером списка нужно использовать символ *, как во всём проекте.

2021-06-27 13:18 UTC, xvitaly commented on source/administration.rst
> +BTRFS поддерживает прозрачное сжатие файлов на разделе. Можно выбрать один из трёх алгоритмов: **zstd**, **zlib**, **lzo**. Сжатие включается через указание параметров монтирования раздела.
Также добавить ссылку на якорь.

2021-06-28 08:27 UTC, cyberMe commented
> Если переместить в раздел Tips and Tricks, то будет нормально, на мой взгляд.

Перенёс в Tips and Tricks

2021-06-28 08:28 UTC, cyberMe commented on source/administration.rst
> +=========================================
Исправил

2021-06-28 08:28 UTC, cyberMe commented on source/administration.rst
> +BTRFS использует двухуровневую структуру хранения данных: пространство поделено на *фрагменты*, которые содержат *блоки данных*. При длительной эксплуатации в файловой системе может возникать большое
Добавил

2021-06-28 08:28 UTC, cyberMe commented on source/administration.rst
> +- `SysadminGuide <https://btrfs.wiki.kernel.org/index.php/SysadminGuide#Balancing>`_
Исправил

2021-06-28 08:28 UTC, cyberMe commented on source/administration.rst
> +BTRFS поддерживает прозрачное сжатие файлов на разделе. Можно выбрать один из трёх алгоритмов: **zstd**, **zlib**, **lzo**. Сжатие включается через указание параметров монтирования раздела.
Сделал

2021-06-28 08:50 UTC, xvitaly approved these changes
LGTM now. Thanks for your contribution. Merged.

2021-06-28 08:51 UTC, merged