Вычитка и актуализация информации
RussianFedora/FAQ pull request #98
Opened 2021-08-21 10:01 UTC by jsonguard

Подробно опишите какие изменения в проект вносит данный pull request:

2021-08-21 11:16 UTC, xvitaly requested changes
Прошу внести небольшие поправки.

2021-08-21 11:16 UTC, xvitaly commented on source/administration.rst
> +Для передачи параметра необходимо в меню загрузчика Grub 2 выбрать нужную загрузочную опцию и нажать клавишу **E** на клавиатуре для перехода в режим редактирвоания.
Получилась тавтология. Два предложения начинаются одинаково.

Также хотелось бы всё привести к единому стилю, если уж взялись редактировать, т.е. вместо "нужно выбрать" укажем "выберем", вместо "нужно нажать клавишу" - "нажмём клавишу" и т.д.

2021-08-21 11:16 UTC, xvitaly commented on source/administration.rst
> +Для начала загрузки нажмите сочетание **Ctrl + X** на клавиатуре.
Здесь аналогично - "нажмём".

2021-08-21 11:16 UTC, xvitaly commented on source/package-manager.rst
> +Да. По умолчанию dnf сохраняет 3 последних ядра, чтобы в случае сбоя была возможность загрузки в более старое для исправления проблем и восстановления работы системы.
Наверное будет лучше и слово "исправления" заменить на "для разрешения проблем и восстановления работы".

2021-08-21 11:16 UTC, xvitaly commented on source/package-manager.rst
> +Обычно DNF корректно определяет тип авторизации, используемый прокси-сервером, но иногда (в случае HTTP-прокси) этот механизм работает некорретно. В случае возникновения проблем с авторизацией достат
Нужно исправить тавтологию во втором предложении например на "В этом случае достаточно...".

2021-08-21 11:16 UTC, xvitaly commented on source/package-manager.rst
> +    * ``basic`` -- базовая HTTP аутентификация, вероятно вы используете именно этот метод;
Отступ от начала строки для списков в проекте должен быть равен 2 пробелам.

2021-08-21 11:18 UTC, xvitaly commented on source/package-manager.rst
> +Подробнее о поддерживаемых методах аутентификации см. `в документации<https://dnf.readthedocs.io/en/latest/conf_ref.html#options-for-both-main-and-repo>`.
Требуется пробел после слова "документации". В конце требуется добавить два символа подчёркивания.

Пример:

```
`пример <https://example.org>`__
```

2021-08-21 13:57 UTC, jsonguard commented on source/administration.rst
> +Для передачи параметра необходимо в меню загрузчика Grub 2 выбрать нужную загрузочную опцию и нажать клавишу **E** на клавиатуре для перехода в режим редактирвоания.
Правильно ли я понимаю, что и в дальнейшем для ответов в стиле "how to do X" следует использовать этот стиль?

2021-08-21 15:56 UTC, xvitaly commented on source/administration.rst
> +Для передачи параметра необходимо в меню загрузчика Grub 2 выбрать нужную загрузочную опцию и нажать клавишу **E** на клавиатуре для перехода в режим редактирвоания.
Да. Этот стиль уже давно применяется в FAQ.

2021-08-21 16:01 UTC, xvitaly requested changes
Нужно исправить опечатки и перефразировать одно предложение из-за возникшей тавтологии.

2021-08-21 16:01 UTC, xvitaly commented on source/package-manager.rst
> +Да, это возможно     . В настоящее время поддерживаются следующие версии Java. Допускатся их одновр:еменная установка.
1. Лишние пробелы после слова "возможно".
2. Опечатка в словах "Допускатся" и "одновр:еменная".

2021-08-22 09:44 UTC, xvitaly approved these changes
LGTM. Thanks for your contribution.

2021-08-22 09:45 UTC, merged